# Credenziali utenti (password hashate con bcrypt)
[passwords]
admin = "$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj3QJ/8qHqKi"  # password123
utente = "$2b$12$8K1p/a0dL1LXMIgoEDFrwOe6J7K8K1p/a0dL1LXMIgoEDFrwOe6J7"  # demo
SACHIN = "$2b$12$meta2026_hash_here"
MICHELE = "$2b$12$meta2026_hash_here"
SANDRA = "$2b$12$meta2026_hash_here"
SEDE = "$2b$12$meta2026_hash_here"

# Configurazione database (opzionale per futuro)
[database]
url = "sqlite:///prima_nota.db"

# Configurazione backup
[backup]
enabled = true
frequency = "daily" 